# Generated by Django 5.1.15 on 2026-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hisob nomi')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Balans')),
                ('currency', models.CharField(choices=[('UZS', 'Oʻzbek soʻmi (UZS)'), ('USD', 'AQSH dollari (USD)'), ('EUR', 'Yevro (EUR)')], default='UZS', max_length=5, verbose_name='Valyuta')),
                ('icon', models.CharField(default='wallet', max_length=50, verbose_name='Ikonka')),
                ('color', models.CharField(default='#4CAF50', max_length=20, verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hisob',
                'verbose_name_plural': 'Hisoblar',
                'ordering': ['-created_at'],
            },
        ),
    ]
