# Generated by Django 5.1.15 on 2026-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (Oʻzbekcha)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (Ruscha)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nomi (Inglizcha)')),
                ('type', models.CharField(choices=[('EXPENSE', 'Chiqim'), ('INCOME', 'Kirim')], default='EXPENSE', max_length=10, verbose_name='Turi')),
                ('icon', models.CharField(default='grid', max_length=50, verbose_name='Ikonka')),
                ('color', models.CharField(default='#3F51B5', max_length=20, verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['type', 'id'],
            },
        ),
    ]
